# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cfc5db4ca83a6e154b745873d27d241cba89b8be1cb8693f5e3a0edb8cc3e4e90a6b29fa92726eda6fbf72ec0949727dad2b1e1e69601cd690f950a181e40ae

test:
  secret_key_base: a9490213c0531fa13673a573c922788f8b902721a03b88b4e1402b52effda43edd683b570c7cfdcde4b30537363ad3dc1d8e3b55d2f77551290dd2cd5766628e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
